name: Build for ARM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    

    - name: Install libcurl development package
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev build-essential libgmp-dev libssl-dev libcurl4 libgmp10 libstdc++6 libm6 libgcc1 libc6

    - name: Run armbuild-all.sh
      run: |
        chmod +x armbuild-all.sh
        ./armbuild-all.sh
        
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
          name: my-artifact
          path: .


# Add any additional steps or jobs as needed.
