name: Build for ARM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install libcurl development package
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

    - name: Run armbuild-all.sh and copy files to root
      run: |
        chmod +x armbuild-all.sh
        ./armbuild-all.sh
        ls -R  # Add this line for debugging
        rsync -a build/ .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: .  # Upload all files in the root directory
