name: Cross Compile cpuminer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Container
      uses: addnab/docker-run-action@v3
      with:
        image: openwrtorg/sdk:latest
        options: -v ${{ github.workspace }}:/home/build
        run: |
          # 以下命令在 OpenWrt 容器内执行
          
          # 更新软件包列表
          opkg update
          
          # 安装编译工具和依赖
          opkg install gcc make autoconf automake libtool
          opkg install libcurl libssl

    - name: Compile cpuminer
      run: |
        # 切换到代码目录
        cd /home/build

        # 如果需要，运行配置脚本
        # ./autogen.sh

        # 配置编译环境（需要根据实际情况调整）
        ./configure

        # 编译
        make
