name: Build for ARM

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install libcurl development package
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

    - name: Run armbuild-all.sh
      run: chmod +x armbuild-all.sh && ./armbuild-all.sh
